# Generated by Django 3.1.3 on 2020-11-12 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True, max_length=255, null=True)),
                ('entry_date', models.DateTimeField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='membro_photos')),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor a pagar')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor Pago')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciamento.membro')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
