# Generated by Django 3.1.3 on 2020-11-13 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0006_auto_20201113_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamentos',
            name='plano',
        ),
        migrations.AddField(
            model_name='pagamentos',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.planofamilia'),
        ),
    ]
