# Generated by Django 3.2.5 on 2021-08-01 22:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.banco')),
            ],
            options={
                'verbose_name': 'Forma Pagamento',
                'verbose_name_plural': 'Formas de Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True, max_length=255, null=True)),
                ('entry_date', models.DateTimeField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='membro_photos')),
                ('ativo', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='PlanoFamilia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Plano',
            },
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço por mês')),
                ('months', models.IntegerField(default=1, verbose_name='Quant meses')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor Pago')),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('form_pay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.formapagamento')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciamento.membro')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.planofamilia')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
