# Generated by Django 4.1.1 on 2022-11-06 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codBank', models.IntegerField(default=0, unique=True)),
                ('nameBank', models.CharField(max_length=100)),
                ('fullName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('data_entrada', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='membro_photos')),
                ('status', models.BooleanField(default=1)),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='membro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.bank')),
            ],
            options={
                'verbose_name': 'Forma Pagamento',
                'verbose_name_plural': 'Formas de Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='PlanFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFamilyPlan', models.CharField(choices=[('NETFLIX', 'netflix'), ('SPOTIFY', 'spotify'), ('NENHUM', 'nenhum')], default='NENHUM', max_length=9)),
            ],
            options={
                'verbose_name': 'Plano Familia',
            },
        ),
        migrations.CreateModel(
            name='TypePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantidade_meses', models.IntegerField(default=1, verbose_name='Quant meses')),
                ('quantidade_dias', models.IntegerField(default=30, verbose_name='Quant dias')),
            ],
            options={
                'verbose_name': 'Tipos de Planos',
                'verbose_name_plural': 'Tipos de Planos',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data pagamento')),
                ('date_vencimento', models.DateField(blank=True, null=True, verbose_name='Referencia')),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('form_pay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.paymentmethod')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciamento.membro')),
                ('plan_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.planfamily')),
                ('type_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.typeplan')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ('-date_emissao',),
            },
        ),
    ]
