# Generated by Django 4.1.1 on 2022-11-17 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_banco', models.IntegerField(default=0, unique=True)),
                ('nome_banco', models.CharField(max_length=100)),
                ('nome_completo_banco', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fatura', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fatura')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor')),
                ('data_emissao', models.DateField(verbose_name='Data Emissão')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Vencimento')),
                ('nota', models.TextField(blank=True, max_length=255, null=True, verbose_name='Nota')),
                ('plano_familia', models.CharField(choices=[('NETFLIX', 'Netflix'), ('SPOTIFY', 'Spotify'), ('NENHUM', 'nenhum')], default='NENHUM', max_length=9, verbose_name='Plano familia')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('ATRASADO', 'Atrasado'), ('PAGO', 'Pago')], default='ABERTO', max_length=9)),
            ],
            options={
                'verbose_name': 'Contrato do Plano',
                'verbose_name_plural': 'Contratos dos Planos',
            },
        ),
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.banco')),
            ],
            options={
                'verbose_name': 'Metodo de Recebimento do Pagamento',
                'verbose_name_plural': 'Metodos de Recebimento do Pagamento',
            },
        ),
        migrations.CreateModel(
            name='TempoPlano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Plano')),
                ('quantidade_meses', models.IntegerField(default=1, verbose_name='Quant meses')),
                ('quantidade_dias', models.IntegerField(default=30, verbose_name='Quant dias')),
            ],
            options={
                'verbose_name': 'Tempo do plano',
                'verbose_name_plural': 'Tempo dos Planos',
            },
        ),
        migrations.CreateModel(
            name='PagamentosFatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now, verbose_name='Data pagamento')),
                ('nota', models.TextField(blank=True, max_length=255, null=True, verbose_name='Notas')),
                ('fatura_plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.fatura')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.metodopagamento')),
            ],
            options={
                'verbose_name': 'Pagamento de Fatura',
                'verbose_name_plural': 'Pagamentos dos Faturas',
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('data_entrada', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='membro_photos')),
                ('status', models.BooleanField(default=1)),
                ('nota', models.TextField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='membro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ('nome',),
            },
        ),
        migrations.AddField(
            model_name='fatura',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciamento.membro'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='tempo_plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.tempoplano'),
        ),
    ]
