# Generated by Django 4.1.1 on 2022-11-10 05:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contrato', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do contrato')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor')),
                ('date_emissao', models.DateField(verbose_name='Data Emissão')),
                ('date_vencimento', models.DateField(blank=True, null=True, verbose_name='Vencimento')),
                ('note', models.TextField(blank=True, max_length=255, null=True, verbose_name='Nota')),
                ('plan_family', models.CharField(choices=[('NETFLIX', 'Netflix'), ('SPOTIFY', 'Spotify'), ('NENHUM', 'nenhum')], default='NENHUM', max_length=9, verbose_name='Plano familia')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('ATRASADO', 'Atrasado'), ('PAGO', 'Pago')], default='ABERTO', max_length=9)),
            ],
            options={
                'verbose_name': 'Contrato do Plano',
                'verbose_name_plural': 'Contratos dos Planos',
            },
        ),
        migrations.CreateModel(
            name='PlanContractPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now, verbose_name='Data pagamento')),
                ('nota', models.TextField(blank=True, max_length=255, null=True, verbose_name='Notas')),
                ('contrato_plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.plancontract')),
            ],
            options={
                'verbose_name': 'Pagamento de Contrato',
                'verbose_name_plural': 'Pagamentos dos Contratos',
            },
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Banco', 'verbose_name_plural': 'Bancos'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Metodo de Recebimento do Pagamento', 'verbose_name_plural': 'Metodos de Recebimento do Pagamento'},
        ),
        migrations.AlterField(
            model_name='bank',
            name='codBank',
            field=models.IntegerField(default=0, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='fullName',
            field=models.CharField(max_length=250, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='nameBank',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='typeplan',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome do Plano'),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='PlanFamily',
        ),
        migrations.AddField(
            model_name='plancontractpayment',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.paymentmethod'),
        ),
        migrations.AddField(
            model_name='plancontract',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciamento.membro'),
        ),
        migrations.AddField(
            model_name='plancontract',
            name='tipo_plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.typeplan'),
        ),
    ]
