# Generated by Django 4.1.1 on 2022-11-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Banco', 'verbose_name_plural': 'Bancos'},
        ),
        migrations.AlterField(
            model_name='bank',
            name='codBank',
            field=models.IntegerField(default=0, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='fullName',
            field=models.CharField(max_length=250, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='nameBank',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_family',
            field=models.CharField(choices=[('NETFLIX', 'Netflix'), ('SPOTIFY', 'Spotify'), ('NENHUM', 'nenhum')], default='NENHUM', max_length=9),
        ),
        migrations.AlterField(
            model_name='typeplan',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome do Plano'),
        ),
        migrations.DeleteModel(
            name='PlanFamily',
        ),
    ]
