# Generated by Django 3.1.3 on 2020-11-12 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_auto_20201112_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentos',
            name='form_pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.formapagamento'),
        ),
    ]
