# Generated by Django 3.2.5 on 2022-08-26 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_auto_20220807_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membro',
            options={'ordering': ('name',), 'verbose_name': 'Membro', 'verbose_name_plural': 'Membros'},
        ),
        migrations.AlterModelOptions(
            name='quantidadediaspago',
            options={'verbose_name': 'Quantidade dia'},
        ),
        migrations.RenameField(
            model_name='membro',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='last_name',
        ),
    ]
