# Generated by Django 4.1.1 on 2022-11-06 06:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_alter_bank_options_alter_bank_codbank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data pagamento')),
                ('date_vencimento', models.DateField(blank=True, null=True, verbose_name='date Vencimento')),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('plan_family', models.CharField(choices=[('NETFLIX', 'Netflix'), ('SPOTIFY', 'Spotify'), ('NENHUM', 'nenhum')], default='NENHUM', max_length=9)),
                ('form_pay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.paymentmethod')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciamento.membro')),
                ('type_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.typeplan')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ('-date_emissao',),
            },
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
