# Generated by Django 3.2.5 on 2022-08-26 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0003_auto_20220825_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamentos',
            options={'ordering': ('data_pagamento',), 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AlterModelOptions(
            name='quantidadediaspago',
            options={'verbose_name': 'Quantitativo de dias pagos'},
        ),
        migrations.RenameField(
            model_name='quantidadediaspago',
            old_name='quant_meses',
            new_name='quantidade',
        ),
    ]
