# Generated by Django 3.2.5 on 2022-08-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0004_auto_20220825_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamentos',
            options={'ordering': ('-data_pagamento',), 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AlterModelOptions(
            name='quantidadediaspago',
            options={'verbose_name': 'Quantitativo de dias', 'verbose_name_plural': 'Quantitativo de dias'},
        ),
        migrations.AlterField(
            model_name='membro',
            name='entry_date',
            field=models.DateField(),
        ),
    ]
