# Generated by Django 4.1.1 on 2022-11-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0005_plancontract_status_alter_plancontract_date_emissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancontract',
            name='status',
            field=models.CharField(choices=[('EMDIA', 'Em dia'), ('ATRASADO', 'Atrasado'), ('NENHUM', 'nenhum')], default='ABERTO', max_length=9),
        ),
    ]
