# Generated by Django 3.1.3 on 2020-11-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0005_planofamilia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planofamilia',
            options={'verbose_name': 'Plano'},
        ),
        migrations.AddField(
            model_name='pagamentos',
            name='plano',
            field=models.ManyToManyField(blank=True, null=True, to='gerenciamento.PlanoFamilia'),
        ),
    ]
