# Generated by Django 4.1.1 on 2022-11-06 06:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0006_alter_plancontract_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanContractPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pay', models.DateField(default=django.utils.timezone.now, verbose_name='Data pagamento')),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('contract_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.plancontract')),
                ('form_pay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.paymentmethod')),
            ],
            options={
                'verbose_name': 'Pagamento do Contrato de Plano',
                'verbose_name_plural': 'Pagamentos do Contratos de Planos',
            },
        ),
    ]
