# Generated by Django 3.2.5 on 2022-08-26 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0006_membro_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membro',
            options={'ordering': ('nome',), 'verbose_name': 'Membro', 'verbose_name_plural': 'Membros'},
        ),
        migrations.RenameField(
            model_name='membro',
            old_name='entry_date',
            new_name='data_entrada',
        ),
        migrations.RenameField(
            model_name='membro',
            old_name='photo',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='membro',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='membro',
            old_name='notes',
            new_name='notas',
        ),
        migrations.RenameField(
            model_name='membro',
            old_name='ativo',
            new_name='status',
        ),
    ]
