# Generated by Django 3.2.5 on 2022-08-26 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0007_auto_20220826_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banco',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='formapagamento',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='planofamilia',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='quantidadediaspago',
            old_name='name',
            new_name='nome',
        ),
    ]
