# Generated by Django 3.2.5 on 2022-08-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0008_auto_20220826_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentos',
            name='notas',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
