# Generated by Django 3.2.5 on 2022-08-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0009_pagamentos_notas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantidadediaspago',
            old_name='quantidade',
            new_name='quantidade_meses',
        ),
        migrations.AddField(
            model_name='quantidadediaspago',
            name='quantidade_dias',
            field=models.IntegerField(default=30, verbose_name='Quant dias'),
        ),
    ]
