# Generated by Django 3.2.5 on 2022-08-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0010_auto_20220827_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantidadediaspago',
            name='quantidade_meses',
            field=models.IntegerField(default=1, verbose_name='Quant meses'),
        ),
    ]
