# Generated by Django 3.2.5 on 2022-08-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0011_alter_quantidadediaspago_quantidade_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentos',
            name='data_referente',
            field=models.DateField(blank=True, null=True, verbose_name='Data pagamento'),
        ),
    ]
