# Generated by Django 4.1.1 on 2022-11-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0012_pagamentos_data_referente'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='fullName',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagamentos',
            name='data_referente',
            field=models.DateField(blank=True, null=True, verbose_name='Referencia'),
        ),
    ]
