# Generated by Django 4.1.1 on 2022-11-05 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gerenciamento', '0013_banco_fullname_alter_pagamentos_data_referente'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='membro', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
